import Head from "next/head";
import { Client } from "@/graphql/client";

export default function Home({ CMSPageData, categoriesList }: any) {
  console.log(CMSPageData, "CMSPageData");
  const sanitizedHtml = CMSPageData?.data?.cmsPage?.content ;
  return (
    <>
      <Head>
        <title>Project Name</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Render the CMS page data */}
      <div>
      <div
      dangerouslySetInnerHTML={{ __html: sanitizedHtml }}
    />
        
      </div>
    </>
  );
}

export async function getStaticProps() {
  const client = new Client();
  let CMSPageData = null;

  try {
    CMSPageData = await client.fetchCMSPages();
  } catch (error) {

  }

  
  return {
    props: {
      CMSPageData,

    },
   
  };
}

 
